module.exports = [
  {
    id: 1,
    medicine_name: "Tylenol",
    amount_remaining: 40.0,
    user_id: 2,
    refill_reminder: true,
    refill_reminder_date: 1707420639000,
    timezone: "America/Vancouver",
    refilled_on: 1706643039,
    amount_unit: "pills",
  },
  {
    id: 2,
    medicine_name: "Penicillin",
    amount_remaining: 35.0,
    user_id: 1,
    refill_reminder: false,
    timezone: "America/Vancouver",
    refilled_on: 1706470239000,
    amount_unit: "pills",
  },
  {
    id: 3,
    medicine_name: "Testing",
    amount_remaining: 35.0,
    user_id: 1,
    refill_reminder: true,
    refill_reminder_date: 1707247839000,
    timezone: "America/Vancouver",
    refilled_on: 1706470239,
    amount_unit: "pills",
  },
];
